spring:
  application:
    name: auth-service

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false


    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: never
