spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web: TRACE
    org.springframework.web: DEBUG
#   org.hibernate.SQL: DEBUG

